DROP TABLE IF EXISTS branches;

DROP TABLE IF EXISTS convo_summaries;
DROP TABLE IF EXISTS plan_builds;

DROP TABLE IF EXISTS users_projects;
DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS orgs_users;

DROP TABLE IF EXISTS email_verifications;
DROP TABLE IF EXISTS auth_tokens;
DROP TABLE IF EXISTS invites;

DROP TABLE IF EXISTS orgs;
DROP TABLE IF EXISTS users;
