DROP TABLE IF EXISTS orgs;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS orgs_users;
DROP TABLE IF EXISTS users_projects;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS convo_summaries;
DROP TABLE IF EXISTS plan_builds;
